### ISSUE TITLE
NameError in Map::Leaflet#index after updating to 1.0.3

### ISSUE THREAD

**Issue by hambrrrglar** [Freika/dawarich#2214]
After updating to 1.0.2, I put my email address under the supporters.  It said it can't find my email (which is the same one as I use for Patreon).  It doesn't really matter that it doesn't work, but I cannot remove my email and save a blank one anymore.  When I update to 1.0.3, this is the error when I pull open the homepage now:

NameError in Map::Leaflet#index
Showing /var/app/app/views/shared/_navbar.html.erb where line #146 raised:

undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f4b8fe32448>
Extracted source (around line #146):
144
145
146
147
148
149
              
          <ul tabindex="0" class="dropdown-content menu menu-sm mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Settings', settings_path %></li>
            <% if !DawarichSettings.self_hosted? %>
              <li><%= link_to 'Subscription', "#{MANAGER_URL}/auth/dawarich?token=#{current_user.generate_subscription_token}" %></li>
            <% end %>

Trace of template inclusion: #<ActionView::Template app/views/layouts/map.html.erb locals=[]>

Rails.root: /var/app

Application Trace | Framework Trace | Full Trace
app/views/shared/_navbar.html.erb:146
app/views/layouts/map.html.erb:29
Request
Parameters:

None
Toggle session dump
Toggle env dump
Response
Headers:

None

**Comment by pelluch** [comment]
Why did you close this? I am having the same issue, did you find a way around it?

**Comment by nuiler** [comment]
I have this error too
