### ISSUE TITLE
NameError in Map::Maplibre#index after 1.0.1 -> 1.0.3

### ISSUE THREAD

**Issue by eng3** [Freika/dawarich#2223]
**Version**
1.0.3 docker

**Describe the bug**
After upgrading from 1.0.1, and after login, I see: 

```
NameError in Map::Maplibre#index

Showing /var/app/app/views/shared/_navbar.html.erb where line #146 raised:

undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f5a9c014390>

Extracted source (around line #146):

144
145
146
147
148
149
              

	

          <ul tabindex="0" class="dropdown-content menu menu-sm mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Settings', settings_path %></li>
            <% if !DawarichSettings.self_hosted? %>
              <li><%= link_to 'Subscription', "#{MANAGER_URL}/auth/dawarich?token=#{current_user.generate_subscription_token}" %></li>
            <% end %>

Trace of template inclusion: #<ActionView::Template app/views/layouts/map.html.erb locals=[]>

Rails.root: /var/app
Application Trace | Framework Trace | Full Trace
app/views/shared/_navbar.html.erb:146
app/views/layouts/map.html.erb:29 
```

Log:

```
 ⚠️ Starting Rails environment: development ⚠️
 📦 Syncing static assets to public volume...
 ✅ Static assets synced!
 Setting up all required databases...
 Attempting to create database dawarich_development if it doesn't exist...
 Note: Database dawarich_development may already exist or couldn't be created now
 ⏳ Waiting for database dawarich_development to be ready...
 ✅ PostgreSQL database dawarich_development is ready!
 Running migrations for all databases...
 Running primary database migrations...
 [dotenv] Set OBJC_DISABLE_INITIALIZE_FORK_SAFETY
 [dotenv] Loaded .env.development
 OIDC: Not configured (missing OIDC_CLIENT_ID or OIDC_CLIENT_SECRET)
    (0.3ms)  SELECT pg_try_advisory_lock(1212213197400985920)
   ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   ActiveRecord::InternalMetadata Load (0.7ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
    (0.2ms)  SELECT pg_advisory_unlock(1212213197400985920)
   ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
 Running DATA migrations...
 [dotenv] Set OBJC_DISABLE_INITIALIZE_FORK_SAFETY
 [dotenv] Loaded .env.development
 OIDC: Not configured (missing OIDC_CLIENT_ID or OIDC_CLIENT_SECRET)
    (0.3ms)  SELECT pg_try_advisory_lock(1212213197400985920)
   DataMigrate::DataSchemaMigration Load (1.0ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
   ActiveRecord::InternalMetadata Load (0.5ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
    (0.2ms)  SELECT pg_advisory_unlock(1212213197400985920)
   DataMigrate::DataSchemaMigration Load (0.2ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
 Running seeds...
 [dotenv] Set OBJC_DISABLE_INITIALIZE_FORK_SAFETY
 [dotenv] Loaded .env.development
 OIDC: Not configured (missing OIDC_CLIENT_ID or OIDC_CLIENT_SECRET)
   ActiveRecord::SchemaMigration Load (0.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   User Exists? (0.6ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
   Country Exists? (0.5ms)  SELECT 1 AS one FROM "countries" LIMIT $1  [["LIMIT", 1]]
   Tag Exists? (0.4ms)  SELECT 1 AS one FROM "tags" LIMIT $1  [["LIMIT", 1]]
 => Booting Puma
 => Rails 8.0.3 application starting in development
 => Run `bin/rails server --help` for more startup options
 [dotenv] Set OBJC_DISABLE_INITIALIZE_FORK_SAFETY
 [dotenv] Loaded .env.development
 OIDC: Not configured (missing OIDC_CLIENT_ID or OIDC_CLIENT_SECRET)
 INFO  2026-02-01T15:24:41.570Z pid=61 tid=1rx: Sidekiq 8.0.10 connecting to Redis with options {size: 10, pool_name: "internal", url: "redis://redis:6379/1", db: 1}
 Enqueued Cache::CleaningJob (Job ID: 7e95739a-a735-4170-9473-6c76de1c2f6a) to Sidekiq(cache)
 ↳ config/initializers/cache_jobs.rb:6:in 'block in <main>'
 Enqueued Cache::PreheatingJob (Job ID: 1233b626-23c6-4dcc-8624-46aef163ca2c) to Sidekiq(cache)
 ↳ config/initializers/cache_jobs.rb:8:in 'block in <main>'
 [61] Puma starting in cluster mode...
 [61] * Puma version: 7.1.0 ("Neon Witch")
 [61] * Ruby version: ruby 3.4.6 (2025-09-16 revision dbd83256b1) +YJIT +PRISM [x86_64-linux]
 [61] *  Min threads: 5
 [61] *  Max threads: 5
 [61] *  Environment: development
 [61] *   Master PID: 61
 [61] *      Workers: 2
 [61] *     Restarts: (✔) hot (✖) phased (✖) refork
 [61] * Preloading application
 [61] * Listening on http://[::]:3000
 [61] Use Ctrl-C to stop
 [61] - Worker 0 (PID: 83) booted in 0.0s, phase: 0
 [61] - Worker 1 (PID: 91) booted in 0.0s, phase: 0
   ActiveRecord::SchemaMigration Load (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."api_key" IS NULL LIMIT $1  [["LIMIT", 1]]
   ↳ app/controllers/api_controller.rb:36:in 'ApiController#current_api_user'
 {"method":"GET","path":"/api/v1/health","format":"*/*","controller":"Api::V1::HealthController","action":"index","status":200,"allocations":9256,"duration":39.76,"view":0.3,"db":6.53}


 {"method":"GET","path":"/map/v2","format":"html","controller":"Map::MaplibreController","action":"index","status":500,"allocations":160266,"duration":399.33,"view":0.0,"db":23.74}

 ActionView::Template::Error (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f93a323dd48>)
 Caused by: NameError (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f93a323dd48>)

 Information for: ActionView::Template::Error (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f93a323dd48>):
     143:           </label>
     144:           <ul tabindex="0" class="dropdown-content menu menu-sm mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
     145:             <li><%= link_to 'Account', edit_user_registration_path %></li>
     146:             <li><%= link_to 'Settings', settings_path %></li>
     147:             <% if !DawarichSettings.self_hosted? %>
     148:               <li><%= link_to 'Subscription', "#{MANAGER_URL}/auth/dawarich?token=#{current_user.generate_subscription_token}" %></li>
     149:             <% end %>

 app/views/shared/_navbar.html.erb:146
 app/views/layouts/map.html.erb:29

 Information for cause: NameError (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f93a323dd48>):

 app/views/shared/_navbar.html.erb:146
 app/views/layouts/map.html.erb:29
```

**Comment by Freika** [comment]
Fixed in 1.0.4
