### ISSUE TITLE
500 internal server error when accessing /places page

### ISSUE THREAD

**Issue by whimsical-c4lic0** [Freika/dawarich#2826]
**OS & Hardware**
Docker

**Version**
1.7.10

**Describe the bug**
After updating from 1.7.2 to 1.7.10, when navigating to `/places` I get a 500 internal server error.

**To Reproduce**
1. Login
2. Go to `/places`

**Expected behavior**
The page would load without an error.

**Logs**
```
{"method":null,"path":null,"format":null,"params":{},"controller":"ApplicationCable::Connection","action":"disconnect","status":200,"allocations":16,"duration":0.15}
{"method":null,"path":null,"format":null,"params":{},"controller":"ApplicationCable::Connection","action":"disconnect","status":200,"allocations":15,"duration":0.05}
{"method":"GET","path":"/places","format":"html","controller":"PlacesController","action":"index","status":500,"allocations":3763,"duration":11.32,"view":0.0,"db":1.76}
  
ActionView::Template::Error (undefined method 'y' for nil)
Caused by: NoMethodError (undefined method 'y' for nil)

Information for: ActionView::Template::Error (undefined method 'y' for nil):
    39:               <tr>
    40:                 <td><%= place.name %></td>
    41:                 <td><%= human_datetime(place.created_at, current_user.safe_settings.timezone) %></td>
    42:                 <td><%= "#{place.lat}, #{place.lon}" %></td>
    43:                 <td>
    44:                   <%= link_to 'Delete', place, data: { turbo_confirm: "Are you sure? Deleting a place will result in deleting all visits for this place.", turbo_method: :delete }, class: "px-4 py-2 bg-red-500 text-white rounded-md" %>
    45:                 </td>
  
app/models/place.rb:30:in 'Place#lat'
app/views/places/index.html.erb:42
app/views/places/index.html.erb:38
app/controllers/application_controller.rb:134:in 'ApplicationController#set_user_time_zone'

Information for cause: NoMethodError (undefined method 'y' for nil):
  
app/models/place.rb:30:in 'Place#lat'
app/views/places/index.html.erb:42
app/views/places/index.html.erb:38
app/controllers/application_controller.rb:134:in 'ApplicationController#set_user_time_zone'
```

**Comment by whimsical-c4lic0** [comment]
In case it helps debugging, I still have the same issue after upgrading to 1.7.11

**Comment by Freika** [comment]
In console run:

```ruby
User.find_each do |user|
  DataMigrations::MigratePlacesLonlatJob.perform_now(user.id)
end
```

It should fix your issue

**Comment by whimsical-c4lic0** [comment]
I ran the migration and restarted the container. I'm still getting the 500 error when navigating to `/places` though

```bash
❯ docker exec -it dawarich /bin/sh
# bin/rails console
OIDC: Not configured (missing OIDC_CLIENT_ID or OIDC_CLIENT_SECRET)
Loading production environment (Rails 8.0.5)
dawarich(prod)* User.find_each do |user|
dawarich(prod)*   DataMigrations::MigratePlacesLonlatJob.perform_now(user.id)
dawarich(prod)> end
Performing DataMigrations::MigratePlacesLonlatJob (Job ID: 41bd06c4-8ff3-4dec-af4f-2a49fc925bf4) from Sidekiq(data_migrations) with arguments: 1
Performed DataMigrations::MigratePlacesLonlatJob (Job ID: 41bd06c4-8ff3-4dec-af4f-2a49fc925bf4) from Sidekiq(data_migrations) in 94.98ms
=> nil
```

```
{"method":"GET","path":"/places","format":"html","controller":"PlacesController","action":"index","status":500,"allocations":17225,"duration":89.17,"view":0.0,"db":31.6}
  
ActionView::Template::Error (undefined method 'y' for nil)
Caused by: NoMethodError (undefined method 'y' for nil)

Information for: ActionView::Template::Error (undefined method 'y' for nil):
    39:               <tr>
    40:                 <td><%= place.name %></td>
    41:                 <td><%= human_datetime(place.created_at, current_user.safe_settings.timezone) %></td>
    42:                 <td><%= "#{place.lat}, #{place.lon}" %></td>
    43:                 <td>
    44:                   <%= link_to 'Delete', place, data: { turbo_confirm: "Are you sure? Deleting a place will result in deleting all visits for this place.", turbo_method: :delete }, class: "px-4 py-2 bg-red-500 text-white rounded-md" %>
    45:                 </td>
  
app/models/place.rb:31:in 'Place#lat'
app/views/places/index.html.erb:42
app/views/places/index.html.erb:38
app/controllers/application_controller.rb:134:in 'ApplicationController#set_user_time_zone'

Information for cause: NoMethodError (undefined method 'y' for nil):
  
app/models/place.rb:31:in 'Place#lat'
app/views/places/index.html.erb:42
app/views/places/index.html.erb:38
app/controllers/application_controller.rb:134:in 'ApplicationController#set_user_time_zone'
```
