### ISSUE TITLE
undefined method 'y' for nil still at places after upgrade to 25.2

### ISSUE THREAD

**Issue by MrColumbo** [Freika/dawarich#975]
![Image](https://github.com/user-attachments/assets/719c9bc6-4f3e-4ac7-b2b5-ba57e71f2aa2)

**OS & Hardware**
docker on alpine linux

**Version**
25.2.

**Describe the bug**
places page does not work at all

**To Reproduce**
1. Go to Visits/Places
2. get error message

**Expected behavior**
A list of (suggested) places

**Screenshots**

**Logs**

**Additional context**
Upgrade to 25.2. fixed errors on map and points but visits/places still does not work
that one rake command does not exist ( rake points:migrate_to_lonlat ) ....generally not even rake:points does exist (while rake data_cleanup:remove_duplicate_points works well)

**Comment by MrColumbo** [comment]
not sure why it looked like that one rake command does not exist. I am just running it ....maybe it fixes the issue

**Comment by MrColumbo** [comment]
using rake worked :)
