### ISSUE TITLE
Internal Server Error 500 after update to 1.0.3

### ISSUE THREAD

**Issue by lovwyr** [Freika/dawarich#2215]
**BEFORE OPENING AN ISSUE, MAKE SURE YOU READ THIS: https://github.com/Freika/dawarich/issues/1382**

**OS & Hardware**
Docker version 29.0.2

**Version**
1.0.3 (latest Image)

**Describe the bug**
After upddate Docker deployment to 1.0.3 imitatly after opening the Startpage an Error 500

**To Reproduce**
1. open https://dawarich.xxx.xx
2. get redirect to https://dawarich.xxx.xx/map/v2
3. get Error 500

**Expected behavior**
See the Map  :)

**Screenshots**
Attached

<img width="1693" height="1208" alt="Image" src="https://github.com/user-attachments/assets/875d616b-3eec-4f21-bad1-ecf1b7764885" />

**Logs**
```
method=GET path=/map/v2 format=html controller=Map::MaplibreController action=index status=500 allocations=101667 duration=1115.5 view=0 db=54.4

  

ActionView::Template::Error (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f2d12cec318>)

Caused by: NameError (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f2d12cec318>)



Information for: ActionView::Template::Error (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f2d12cec318>):

    143:           </label>

    144:           <ul tabindex="0" class="dropdown-content menu menu-sm mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">

    145:             <li><%= link_to 'Account', edit_user_registration_path %></li>

    146:             <li><%= link_to 'Settings', settings_path %></li>

    147:             <% if !DawarichSettings.self_hosted? %>

    148:               <li><%= link_to 'Subscription', "#{MANAGER_URL}/auth/dawarich?token=#{current_user.generate_subscription_token}" %></li>

    149:             <% end %>

  

app/views/shared/_navbar.html.erb:146

app/views/layouts/map.html.erb:29



Information for cause: NameError (undefined local variable or method 'settings_path' for an instance of #<Class:0x00007f2d12cec318>):

  

app/views/shared/_navbar.html.erb:146

app/views/layouts/map.html.erb:29

method=GET path=/ format=html controller=HomeController action=index status=302 allocations=3335 duration=70.22 view=0 db=27.52 location=https://dawarich.jd-s.info/map/v2
```

**Comment by lovwyr** [comment]
Roleback to 1.0.1 fixed it for now.

**Comment by hans341** [comment]
Here seems to be the same....
This is what happens after login:

![Image](https://github.com/user-attachments/assets/3cc82938-9169-4adf-b31f-d17dc7281cb2)

**Comment by Freika** [comment]
Fixed in 1.0.4, thanks!
