### ISSUE TITLE
Map no longer working after upgrade to 0.25.4

### ISSUE THREAD

**Issue by aaronczichon** [Freika/dawarich#1023]
**OS & Hardware**
- ARM VPS

**Version**
0.25.4

**Describe the bug**
After upgrading to 0.25.4 I no longer can visit `/map`. It shows a 500 error. Log file produces following:
```bash
I, [2025-04-07T12:24:44.986769 #95]  INFO -- : {"method":"GET","path":"/map","format":"html","controller":"MapController","action":"index","status":500,"allocations":3119,"duration":121.92,"view":0.0,"db":73.29}
E, [2025-04-07T12:24:44.990924 #95] ERROR -- :   
NoMethodError (undefined method 'y' for nil):

app/controllers/map_controller.rb:11:in 'block in MapController#index'
app/controllers/map_controller.rb:11:in 'Array#map'
app/controllers/map_controller.rb:11:in 'MapController#index'
```

I run the suggestion here: https://dawarich.app/docs/updating-guides/#errors-on-the-map-page but this didn't helped.

**Comment by Freika** [comment]
@aaronczichon please provide logs from your attempt to run the [migration commands](https://dawarich.app/docs/updating-guides/#errors-on-the-map-page)

**Comment by aaronczichon** [comment]
Does this help?

![Image](https://github.com/user-attachments/assets/d92c93f2-af2c-4971-bae9-1d411aae4979)

Or is there a logfile where the result is written with more information? :)

**Comment by basnappl** [comment]
Hello, I have this issue, too.  When I try to run the migration command, I get the follwing:
```
[dotenv] Set DATABASE_PORT
[dotenv] Loaded .env.development
Loading development environment (Rails 8.0.1)
[1] pry(main)> User.includes(:tracked_points).find_each do |user|
[1] pry(main)>   user.tracked_points.where(lonlat: nil).update_all('lonlat = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)')
[1] pry(main)> end
D, [2025-04-25T22:07:24.110115 #2909] DEBUG -- :   User Load (15.5ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1000]]
D, [2025-04-25T22:07:40.476770 #2909] DEBUG -- :   Point Load (12698.1ms)  SELECT "points".* FROM "points" WHERE "points"."user_id" IN ($1, $2)  [["user_id", 1], ["user_id", 2]]
D, [2025-04-25T22:07:56.690111 #2909] DEBUG -- :   Point Update All (8.6ms)  UPDATE "points" SET lonlat = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) WHERE "points"."user_id" = $1 AND "points"."lonlat" IS NULL  [["user_id", 1]]
D, [2025-04-25T22:07:57.686933 #2909] DEBUG -- :   Point Update All (993.7ms)  UPDATE "points" SET lonlat = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) WHERE "points"."user_id" = $1 AND "points"."lonlat" IS NULL  [["user_id", 2]]
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_points_on_lonlat_timestamp_user_id" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (lonlat, "timestamp", user_id)=(0101000020E6100000DF35E84B6F9C53C0E4486760E4F54240, 1736631686, 2) already exists.

from /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:162:in 'PG::Connection#exec_params'
Caused by PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_points_on_lonlat_timestamp_user_id"
DETAIL:  Key (lonlat, "timestamp", user_id)=(0101000020E6100000DF35E84B6F9C53C0E4486760E4F54240, 1736631686, 2) already exists.

from /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:162:in 'PG::Connection#exec_params'
[2] pry(main)> 
```
Any suggestions for how to solve this?

**Comment by adamzvolanek** [comment]
> Hello, I have this issue, too. When I try to run the migration command, I get the following:
> 
> ```
> [dotenv] Set DATABASE_PORT
> [dotenv] Loaded .env.development
> Loading development environment (Rails 8.0.1)
> [1] pry(main)> User.includes(:tracked_points).find_each do |user|
> [1] pry(main)>   user.tracked_points.where(lonlat: nil).update_all('lonlat = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)')
> [1] pry(main)> end
> D, [2025-04-25T22:07:24.110115 #2909] DEBUG -- :   User Load (15.5ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1000]]
> D, [2025-04-25T22:07:40.476770 #2909] DEBUG -- :   Point Load (12698.1ms)  SELECT "points".* FROM "points" WHERE "points"."user_id" IN ($1, $2)  [["user_id", 1], ["user_id", 2]]
> D, [2025-04-25T22:07:56.690111 #2909] DEBUG -- :   Point Update All (8.6ms)  UPDATE "points" SET lonlat = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) WHERE "points"."user_id" = $1 AND "points"."lonlat" IS NULL  [["user_id", 1]]
> D, [2025-04-25T22:07:57.686933 #2909] DEBUG -- :   Point Update All (993.7ms)  UPDATE "points" SET lonlat = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) WHERE "points"."user_id" = $1 AND "points"."lonlat" IS NULL  [["user_id", 2]]
> ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_points_on_lonlat_timestamp_user_id" (ActiveRecord::RecordNotUnique)
> DETAIL:  Key (lonlat, "timestamp", user_id)=(0101000020E6100000DF35E84B6F9C53C0E4486760E4F54240, 1736631686, 2) already exists.
> 
> from /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:162:in 'PG::Connection#exec_params'
> Caused by PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_points_on_lonlat_timestamp_user_id"
> DETAIL:  Key (lonlat, "timestamp", user_id)=(0101000020E6100000DF35E84B6F9C53C0E4486760E4F54240, 1736631686, 2) already exists.
> 
> from /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:162:in 'PG::Connection#exec_params'
> [2] pry(main)> 
> ```
> 
> Any suggestions for how to solve this?
> 
> Edited to add: I'm not sure if this is relevant, but I do also see the following message in my docker logs repeated every 10 seconds: `dawarich_db | 2025-04-25 22:11:05.191 UTC [2549] FATAL: database "dawarich_development" does not exist`

The latest release enables map capability again.

**Comment by basnappl** [comment]
> The latest release enables map capability again.

I am on the latest release.
